name: Test & Release
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: pnpm i
        run: pnpm i
      - name: Test
        run: |
          pnpm i
          pnpm test
          pnpm typing
      - name: Build
        run:
          pnpm build
      
      - name: Push to release
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: release # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
